name: "Post to Bluesky"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/7 * * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
      
      - name: Send post
        id: send-post
        run: npm start -- hello
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
